sonar.projectKey=tech-challenge
sonar.projectName=Tech Challenge - Oficina Mecanica
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=src/generated/**,**/*.spec.ts,**/dto/**,**/main.ts,**/*.module.ts,prisma/**,dist/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/unit/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.sourceEncoding=UTF-8
